config/routes.rb
Rails.application.routes.draw do
 

  resources :leaders
  resources :lkup_sugg_statuses
  resources :ci_reviews
  resources :cilisting1s
  
  mount RailsAdmin::Engine => '/radmin', as: 'rails_admin'

  # devise_for :users

  resources :roles
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    match 'active'            => 'users/sessions#active',               via: :get  
    match 'timeout'           => 'users/sessions#timeout',              via: :get   
  end  
  
  root "home#index"

  # get 'home/index'

  # get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/leader.rb
class Leader < ApplicationRecord
  self.table_name = 'leader'
  default_scope {order('fullcommonname ASC')}
end

app/controllers/leaders_controller.rb
class LeadersController < ApplicationController
before_filter :authenticate_user!
  # before_action :set_leader, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource


  # cancancan..
  #load_and_authorize_resource :leader

  # GET /leaders
  def index
    @q = @leaders.search params[:q]
    @leaders = @q.result.page(params[:page])
  end

  # GET /leaders/1
  def show
  end

  # GET /leaders/new
  def new
  end

  # GET /leaders/1/edit
  def edit
  end

  # POST /leaders
  def create
    respond_to do |format|
      if @leader.save
        format.html { redirect_to @leader, notice: t('success_create') }
        format.json { render :show, status: :created, location: @leader }
      else
        format.html { render :new }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaders/1
  def update
    respond_to do |format|
      if @leader.update(leader_params)
        format.html { redirect_to @leader, notice: t('success_update') }
        format.json { render :show, status: :ok, location: @leader }
      else
        format.html { render :edit }
        format.json { render json: @leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaders/1
  def destroy
    @leader.destroy
    respond_to do |format|
      format.html { redirect_to leaders_url, notice: t('success_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def leader_params
    params.require(:leader).permit(:clocknum, :Name, :fullcommonname, :ci_leader, :comment, :updatedtime, :createdtime, :position, :shift, :dept, :Common_Name, :fullname, :Middleproper, :Lastproper, :Firstproper, :First, :Middle, :Last)
  end
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/views/leaders/_form.html.erb
<%= form_for(@leader, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @leader.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@leader.errors.count, "error") %> prohibited this leader from being saved:</h4>
      <ul>
      <% @leader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
            <%= f.label :clocknum, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :clocknum, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Name, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :fullcommonname, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :fullcommonname, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :ci_leader, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :ci_leader, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :comment, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :comment, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :updatedtime, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.datetime_select :updatedtime, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :createdtime, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.datetime_select :createdtime, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :position, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :position, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :shift, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :shift, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :dept, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :dept, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Common_Name, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Common_Name, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :fullname, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :fullname, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Middleproper, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Middleproper, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Lastproper, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Lastproper, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Firstproper, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Firstproper, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :First, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :First, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Middle, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Middle, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :Last, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :Last, class: "form-control" %>
      </div>
        </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/leaders/edit.html.erb
<h1>Editing Leader</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @leader, class: "btn btn-info", :style=>'color:#FFFFFF;' %> &nbsp &nbsp &nbsp
<%= link_to 'Back', leaders_path, class: "btn btn-default" %>

app/views/leaders/index.html.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_leader_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Leaders</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :clocknum_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @leaders %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @leaders, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Clocknum</th>
      <th>Name</th>
      <th>Fullcommonname</th>
      <th>Ci leader</th>
      <th>Comment</th>
      <th>Updatedtime</th>
      <th>Createdtime</th>
      <th>Position</th>
      <th>Shift</th>
      <th>Dept</th>
      <th>Common name</th>
      <th>Fullname</th>
      <th>Middleproper</th>
      <th>Lastproper</th>
      <th>Firstproper</th>
      <th>First</th>
      <th>Middle</th>
      <th>Last</th>
    </tr>
  </thead>

  <tbody>
    <% @leaders.each do |leader| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', leader, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_leader_path(leader), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', leader, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= leader.clocknum %></td>
        <td><%= leader.Name %></td>
        <td><%= leader.fullcommonname %></td>
        <td><%= leader.ci_leader %></td>
        <td><%= leader.comment %></td>
        <td><%= leader.updatedtime %></td>
        <td><%= leader.createdtime %></td>
        <td><%= leader.position %></td>
        <td><%= leader.shift %></td>
        <td><%= leader.dept %></td>
        <td><%= leader.Common_Name %></td>
        <td><%= leader.fullname %></td>
        <td><%= leader.Middleproper %></td>
        <td><%= leader.Lastproper %></td>
        <td><%= leader.Firstproper %></td>
        <td><%= leader.First %></td>
        <td><%= leader.Middle %></td>
        <td><%= leader.Last %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/leaders/new.html.erb
<h1>New Leader</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', leaders_path, class: "btn btn-default" %>

app/views/leaders/show.html.erb
<p>
  <strong>Clocknum:</strong>
  <%= @leader.clocknum %>
</p>

<p>
  <strong>Name:</strong>
  <%= @leader.Name %>
</p>

<p>
  <strong>Fullcommonname:</strong>
  <%= @leader.fullcommonname %>
</p>

<p>
  <strong>Ci leader:</strong>
  <%= @leader.ci_leader %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @leader.comment %>
</p>

<p>
  <strong>Updatedtime:</strong>
  <%= @leader.updatedtime %>
</p>

<p>
  <strong>Createdtime:</strong>
  <%= @leader.createdtime %>
</p>

<p>
  <strong>Position:</strong>
  <%= @leader.position %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @leader.shift %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @leader.dept %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @leader.Common_Name %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @leader.fullname %>
</p>

<p>
  <strong>Middleproper:</strong>
  <%= @leader.Middleproper %>
</p>

<p>
  <strong>Lastproper:</strong>
  <%= @leader.Lastproper %>
</p>

<p>
  <strong>Firstproper:</strong>
  <%= @leader.Firstproper %>
</p>

<p>
  <strong>First:</strong>
  <%= @leader.First %>
</p>

<p>
  <strong>Middle:</strong>
  <%= @leader.Middle %>
</p>

<p>
  <strong>Last:</strong>
  <%= @leader.Last %>
</p>

<br>
<%= link_to 'Edit', edit_leader_path(@leader), class: "btn btn-primary", :style=>'color:#FFFFFF;' %> &nbsp &nbsp
<%= link_to 'Back', leaders_path, class: "btn btn-default" %>