config/routes.rb
Rails.application.routes.draw do
 

  resources :leaders
  resources :lkup_sugg_statuses
  resources :ci_reviews
  resources :cilisting1s
  
  mount RailsAdmin::Engine => '/radmin', as: 'rails_admin'

  # devise_for :users

  resources :roles
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    match 'active'            => 'users/sessions#active',               via: :get  
    match 'timeout'           => 'users/sessions#timeout',              via: :get   
  end  
  
  root "home#index"

  # get 'home/index'

  # get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/lkup_sugg_statuses_controller.rb
class LkupSuggStatusesController < ApplicationController
before_filter :authenticate_user!
  # before_action :set_lkup_sugg_status, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource


  # cancancan..
  #load_and_authorize_resource :lkup_sugg_status

  # GET /lkup_sugg_statuses
  def index
    @q = @lkup_sugg_statuses.search params[:q]
    @lkup_sugg_statuses = @q.result.page(params[:page])
  end

  # GET /lkup_sugg_statuses/1
  def show
  end

  # GET /lkup_sugg_statuses/new
  def new
  end

  # GET /lkup_sugg_statuses/1/edit
  def edit
  end

  # POST /lkup_sugg_statuses
  def create
    respond_to do |format|
      if @lkup_sugg_status.save
        format.html { redirect_to @lkup_sugg_status, notice: t('success_create') }
        format.json { render :show, status: :created, location: @lkup_sugg_status }
      else
        format.html { render :new }
        format.json { render json: @lkup_sugg_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lkup_sugg_statuses/1
  def update
    respond_to do |format|
      if @lkup_sugg_status.update(lkup_sugg_status_params)
        format.html { redirect_to @lkup_sugg_status, notice: t('success_update') }
        format.json { render :show, status: :ok, location: @lkup_sugg_status }
      else
        format.html { render :edit }
        format.json { render json: @lkup_sugg_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lkup_sugg_statuses/1
  def destroy
    @lkup_sugg_status.destroy
    respond_to do |format|
      format.html { redirect_to lkup_sugg_statuses_url, notice: t('success_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def lkup_sugg_status_params
    params.require(:lkup_sugg_status).permit(:name, :sort, :active_status)
  end
end

app/helpers/lkup_sugg_statuses_helper.rb
module LkupSuggStatusesHelper
end

app/views/lkup_sugg_statuses/_form.html.erb
<%= simple_form_for(@lkup_sugg_status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :sort %>
    <%= f.input :active_status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success'%>
  </div>
<% end %>

app/views/lkup_sugg_statuses/edit.html.erb
<h1>Editing Lkup Sugg Status</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @lkup_sugg_status, class: "btn btn-info", :style=>'color:#FFFFFF;' %> &nbsp &nbsp &nbsp
<%= link_to 'Back', lkup_sugg_statuses_path, class: "btn btn-default" %>

app/views/lkup_sugg_statuses/index.html.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_lkup_sugg_status_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Lkup Sugg Statuses</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @lkup_sugg_statuses %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @lkup_sugg_statuses, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Name</th>
      <th>Sort</th>
      <th>Active status</th>
    </tr>
  </thead>

  <tbody>
    <% @lkup_sugg_statuses.each do |lkup_sugg_status| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', lkup_sugg_status, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_lkup_sugg_status_path(lkup_sugg_status), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', lkup_sugg_status, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= lkup_sugg_status.name %></td>
        <td><%= lkup_sugg_status.sort %></td>
        <td><%= lkup_sugg_status.active_status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lkup_sugg_statuses/new.html.erb
<h1>New Lkup Sugg Status</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', lkup_sugg_statuses_path, class: "btn btn-default" %>

app/views/lkup_sugg_statuses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @lkup_sugg_status.name %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @lkup_sugg_status.sort %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @lkup_sugg_status.active_status %>
</p>

<br>
<%= link_to 'Edit', edit_lkup_sugg_status_path(@lkup_sugg_status), class: "btn btn-primary", :style=>'color:#FFFFFF;' %> &nbsp &nbsp
<%= link_to 'Back', lkup_sugg_statuses_path, class: "btn btn-default" %>