config/routes.rb
Rails.application.routes.draw do
 

  resources :leaders
  resources :lkup_sugg_statuses
  resources :ci_reviews
  resources :cilisting1s
  
  mount RailsAdmin::Engine => '/radmin', as: 'rails_admin'

  # devise_for :users

  resources :roles
  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    match 'active'            => 'users/sessions#active',               via: :get  
    match 'timeout'           => 'users/sessions#timeout',              via: :get   
  end  
  
  root "home#index"

  # get 'home/index'

  # get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/ci_reviews_controller.rb
class CiReviewsController < ApplicationController
before_filter :authenticate_user!
  # before_action :set_ci_review, only: [:show, :edit, :update, :destroy]

  #cancancan
  load_and_authorize_resource


  # cancancan..
  #load_and_authorize_resource :ci_review

  # GET /ci_reviews
  def index
    @q = @ci_reviews.search params[:q]
    @ci_reviews = @q.result.page(params[:page])
  end

  # GET /ci_reviews/1
  def show
  end

  # GET /ci_reviews/new
  def new
  end

  # GET /ci_reviews/1/edit
  def edit
  end

  # POST /ci_reviews
  def create
    respond_to do |format|
      if @ci_review.save
        format.html { redirect_to @ci_review, notice: t('success_create') }
        format.json { render :show, status: :created, location: @ci_review }
      else
        format.html { render :new }
        format.json { render json: @ci_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ci_reviews/1
  def update
    respond_to do |format|
      if @ci_review.update(ci_review_params)
        format.html { redirect_to @ci_review, notice: t('success_update') }
        format.json { render :show, status: :ok, location: @ci_review }
      else
        format.html { render :edit }
        format.json { render json: @ci_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ci_reviews/1
  def destroy
    @ci_review.destroy
    respond_to do |format|
      format.html { redirect_to ci_reviews_url, notice: t('success_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def ci_review_params
    params.require(:ci_review).permit(:project_number, :suggestion_status, :owner, :project_description, :comments, :originator, :link, :linkmore, :team, :wc_idea_date, :ciid, :updatedtime)
  end
end

app/helpers/ci_reviews_helper.rb
module CiReviewsHelper
end

app/views/ci_reviews/_form.html.erb
<%= form_for(@ci_review, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @ci_review.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@ci_review.errors.count, "error") %> prohibited this ci_review from being saved:</h4>
      <ul>
      <% @ci_review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
            <%= f.label :project_number, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :project_number, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :suggestion_status, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%#= f.text_field :suggestion_status, class: "form-control" %>
        <%= f.collection_select(:suggestion_status,  LkupSuggStatus.all, :name, :name, {:prompt   => "Select a Status"}, { :class => 'dgselect2' }) %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :owner, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%#= f.text_field :owner, class: "form-control" %>
        <%#= select_tag "answers[#{question.id}]", options_from_collection_for_select(PartNumber.all, :name , :name ) , { :prompt => 'Please Select', :required => true,  :class => 'dgselect2' , :autocomplete => :off }  %>
        <%#= f.collection_select(:brand,  @brands, :name, :name, {:prompt   => "Select a Brand"}, {:id => 'brands_select'}) %>
        <%#= f.collection_select :country_of_origin_id, CountryOfOrigin.all, :id, :name,  { prompt: true }, { :class => 'dgselect2' }  %>
        <%= f.collection_select(:owner,  Leader.all, :fullcommonname, :fullcommonname, {:prompt   => "Select a Name"}, {:id => 'lss_select', :class => 'dgselect2' }) %>

      </div>
  </div>
        
  <div class="form-group">
            <%= f.label :project_description, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :project_description, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :comments, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_area :comments, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :originator, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :originator, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :link, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :link, class: "form-control" %>
        <br><%= link_to "link" , root_url+@ci_review.link_web , { target: '_blank' } %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :linkmore, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :linkmore, class: "form-control" %>
        
        <br><%= link_to "link" , root_url+@ci_review.linkmore_web , { target: '_blank' } %>
        <%#= link_to customer.address, root_url+customer.address , { target: '_blank' } %>
      </div>
        </div>


  <div class="form-group">
            <%= f.label :team, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= f.text_field :team, class: "form-control" %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :wc_idea_date, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= @ci_review.wc_idea_date %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :ciid, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= @ci_review.ciid %>
      </div>
        </div>
  <div class="form-group">
            <%= f.label :updatedtime, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
        <%= @ci_review.updatedtime %>
      </div>
        </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/ci_reviews/edit.html.erb
<h1>Editing Ci Review</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @ci_review, class: "btn btn-info", :style=>'color:#FFFFFF;' %> &nbsp &nbsp &nbsp
<%= link_to 'Back', ci_reviews_path, class: "btn btn-default" %>

app/views/ci_reviews/index.html.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_ci_review_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Ci Reviews</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :project_number_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @ci_reviews %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @ci_reviews, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Project number</th>
      <th>Suggestion status</th>
      <th>Owner</th>
      <th>Project description</th>
      <th>Comments</th>
      <th>Originator</th>
      <th>Link</th>
      <th>Linkmore</th>
      <th>Team</th>
      <th>Wc idea date</th>
      <th>Ciid</th>
      <th>Updatedtime</th>
    </tr>
  </thead>

  <tbody>
    <% @ci_reviews.each do |ci_review| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', ci_review, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_ci_review_path(ci_review), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', ci_review, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= ci_review.project_number %></td>

        <td style="color:green;">        
        <!-- https://github.com/bernat/best_in_place -->
        <%= best_in_place ci_review, :suggestion_status, :as => :select, :collection => LkupSuggStatus.all.map { |i| [i.name, i.name] } %>
        <%#= best_in_place ci_review, :suggestion_status, :as => :select, :collection => LkupSuggStatus.all.map { |i| [i.name, i.name] }, :class => 'dgselect2' %>
        <%#= best_in_place ci_review, :suggestion_status, :type => :select, :collection => %w(Investigate Implement Review PreviouslyPlanned Complete) %>
        <%#= best_in_place ci_review, :suggestion_status, :as => :select, :collection => {"Investigate" => "Investigate", "Implement" => "Implement", "3" => "Germany", "4" => "France"} %>

        </td>

        <td><%= ci_review.owner %></td>
        <td><%= ci_review.project_description %></td>
        <td><%= best_in_place ci_review, :comments, :as => :textarea , :ok_button => 'Save', :cancel_button => 'Cancel' %></td>
        <td><%= ci_review.originator %></td>
        <td><%= ci_review.link %></td>
        <td><%= ci_review.linkmore %></td>
        <td><%= ci_review.team %></td>
        <td><%= ci_review.wc_idea_date %></td>
        <td><%= ci_review.ciid %></td>
        <td><%= ci_review.updatedtime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ci_reviews/index.html__2017-05-20_13.04.12.erb
<row class="row is-table-row" >

  <div class="col-sm-1 ">
    <%= link_to 'Create', new_ci_review_path , class: "btn btn-success"%>
  </div>

  <div class="col-sm-2 ">
    <h4>Listing Ci Reviews</h4>
  </div>

  <div class="col-sm-3">
    <%= search_form_for @q, class: 'search-form' do |f| %>
      <div class="input-group">
        <%= f.search_field :project_number_cont, class: 'form-control' %>
        <span class="input-group-btn">
          <button class="btn btn-primary">Search <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 ">
    <%= paginate @ci_reviews %>
  </div>
  
  <div class="col-sm-2 ">
    <%= page_entries_info @ci_reviews, :entry_name => 'item' %>
  </div>
  
</row>


<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="1"></th>
            <th>Project number</th>
      <th>Suggestion status</th>
      <th>Owner</th>
      <th>Project description</th>
      <th>Comments</th>
      <th>Originator</th>
      <th>Link</th>
      <th>Linkmore</th>
      <th>Team</th>
      <th>Wc idea date</th>
      <th>Ciid</th>
      <th>Updatedtime</th>
    </tr>
  </thead>

  <tbody>
    <% @ci_reviews.each do |ci_review| %>
      <tr>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', ci_review, class: "btn btn-info", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Edit', edit_ci_review_path(ci_review), class: "btn btn-primary", :style=>'color:#FFFFFF;' %>
          <%= link_to 'Destroy', ci_review, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", :style=>'color:#FFFFFF;' %>
          </div>
        </td>
        
        <td><%= ci_review.project_number %></td>
        <td><%= ci_review.suggestion_status %></td>
        <td><%= ci_review.owner %></td>
        <td><%= ci_review.project_description %></td>
        <td><%= ci_review.comments %></td>
        <td><%= ci_review.originator %></td>
        <td><%= ci_review.link %></td>
        <td><%= ci_review.linkmore %></td>
        <td><%= ci_review.team %></td>
        <td><%= ci_review.wc_idea_date %></td>
        <td><%= ci_review.ciid %></td>
        <td><%= ci_review.updatedtime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ci_reviews/new.html.erb
<h1>New Ci Review</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', ci_reviews_path, class: "btn btn-default" %>

app/views/ci_reviews/show.html.erb
<p>
  <strong>Project number:</strong>
  <%= @ci_review.project_number %>
</p>

<p>
  <strong>Suggestion status:</strong>
  <%= @ci_review.suggestion_status %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @ci_review.owner %>
</p>

<p>
  <strong>Project description:</strong>
  <%= @ci_review.project_description %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @ci_review.comments %>
</p>

<p>
  <strong>Originator:</strong>
  <%= @ci_review.originator %>
</p>

<p>
  <strong>Link:</strong>
  <%= @ci_review.link %>
</p>

<p>
  <strong>Linkmore:</strong>
  <%= @ci_review.linkmore %>
</p>

<p>
  <strong>Team:</strong>
  <%= @ci_review.team %>
</p>

<p>
  <strong>Wc idea date:</strong>
  <%= @ci_review.wc_idea_date %>
</p>

<p>
  <strong>Ciid:</strong>
  <%= @ci_review.ciid %>
</p>

<p>
  <strong>Updatedtime:</strong>
  <%= @ci_review.updatedtime %>
</p>

<br>
<%= link_to 'Edit', edit_ci_review_path(@ci_review), class: "btn btn-primary", :style=>'color:#FFFFFF;' %> &nbsp &nbsp
<%= link_to 'Back', ci_reviews_path, class: "btn btn-default" %>